M48
; DRILL file {KiCad 7.0.10} date Thu Jan 11 23:09:00 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-11T23:09:00+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X10.1982Y-1.7157
X10.4258Y-1.7157
T2
X9.0772Y-4.3055
X9.7961Y-1.8209
X10.2394Y-4.3126
M30
